//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        public int OrderId { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> price { get; set; }
        public int customerId { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
    }
}
